name: haskell-book
version: 0.1.0.0
github: "jhamPac/haskell-book"
license: BSD3
author: "jhamPac"
maintainer: "cloud@kevia.me"
copyright: "2021 jhamPac"

extra-source-files:
    - README.md
    - ChangeLog.md
    - src/Thirteen/data/dict.txt

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/jhamPac/haskell-book>

dependencies:
    - base >= 4.7 && < 5
    - random
    - split
    - containers
    - QuickCheck

library:
    source-dirs: src

executables:
    hangman-exe:
        main: hangman/Main.hs
        source-dirs: app
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - haskell-book
    morse-exe:
        main: morse/Main.hs
        source-dirs: app
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - haskell-book

tests:
    hangman-test:
        main: Spec.hs
        source-dirs: test/hangman
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - haskell-book
    morse-test:
        main: Spec.hs
        source-dirs: test/morse
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - haskell-book
    fifteen:
        main: Spec.hs
        source-dirs: test/fifteen
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - haskell-book
